/*
 * Rain_Fall_Animation.asm
 *
 *  Created: 4/10/2017 1:53:52 AM
 *   Author: qbake_0
 */ 
 /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
; ____   _____  _____  _ ___  ______ ___     __    __  
;|  _ \ |  _  ||_   _|| '   || ____ /   |   / /   / / 
;| |_) )| |_| |  | |  | |¯| || /__ / /| |  / /   / /   
;|    / |  _  |  | |  | | | || __// ___ | / /___/ /___
;| |\ \ | | | | _| |_ | | | || | /_/  |_| /_____/_____/
;|_| )_)|_| |_||_____||_| |_||_| 
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Rain_Fall:																													;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp, 0xFF ST X+, temp	ldi temp, 0xFF ST X+, temp	ldi temp, 0xFF ST X+, temp	ldi temp, 0xFF ST X+, temp      ;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
		ldi Subtraction4, 12																								;
Rain_Fall_loop:																												;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp, 0xBF ST X+, temp	ldi temp, 0xFF ST X+, temp	ldi temp, 0xFF ST X+, temp	ldi temp, 0xFF ST X+, temp      ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ldi temp, 0x40 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
		Call Rain_Fall_function																								;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp, 0xBF ST X+, temp	ldi temp, 0xFF ST X+, temp	ldi temp, 0xFF ST X+, temp	ldi temp, 0xFF ST X+, temp      ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
		Call Rain_Fall_function																								;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp, 0xAF ST X+, temp	ldi temp, 0xFF ST X+, temp	ldi temp, 0xFF ST X+, temp	ldi temp, 0xFF ST X+, temp      ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ldi temp, 0x10 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
		Call Rain_Fall_function																								;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp, 0xAF ST X+, temp	ldi temp, 0xFF ST X+, temp	ldi temp, 0xFF ST X+, temp	ldi temp, 0xFF ST X+, temp      ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
		Call Rain_Fall_function																								;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp, 0xAF ST X+, temp	ldi temp, 0xFF ST X+, temp	ldi temp, 0xEF ST X+, temp	ldi temp, 0xFF ST X+, temp      ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x10 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
		Call Rain_Fall_function																								;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp, 0xEF ST X+, temp	ldi temp, 0xFF ST X+, temp	ldi temp, 0xEF ST X+, temp	ldi temp, 0xFF ST X+, temp      ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
		Call Rain_Fall_function																								;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp, 0xEF ST X+, temp	ldi temp, 0xBF ST X+, temp	ldi temp, 0xEF ST X+, temp	ldi temp, 0xFF ST X+, temp      ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x40 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
		Call Rain_Fall_function																								;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp, 0xFF ST X+, temp	ldi temp, 0xBF ST X+, temp	ldi temp, 0xEF ST X+, temp	ldi temp, 0xFF ST X+, temp      ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
		Call Rain_Fall_function																								;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp, 0xFE ST X+, temp	ldi temp, 0xBF ST X+, temp	ldi temp, 0xEF ST X+, temp	ldi temp, 0xFF ST X+, temp      ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ldi temp, 0x01 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
		Call Rain_Fall_function																								;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp, 0xFE ST X+, temp	ldi temp, 0xBF ST X+, temp	ldi temp, 0xFF ST X+, temp	ldi temp, 0xFF ST X+, temp      ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
		Call Rain_Fall_function																								;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp, 0xFE ST X+, temp	ldi temp, 0xBF ST X+, temp	ldi temp, 0xFB ST X+, temp	ldi temp, 0xFF ST X+, temp      ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x04 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
		Call Rain_Fall_function																								;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp, 0xFE ST X+, temp	ldi temp, 0xFF ST X+, temp	ldi temp, 0xFB ST X+, temp	ldi temp, 0xFF ST X+, temp      ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
		Call Rain_Fall_function																								;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp, 0xFE ST X+, temp	ldi temp, 0xFB ST X+, temp	ldi temp, 0xFB ST X+, temp	ldi temp, 0xFF ST X+, temp      ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x04 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
		Call Rain_Fall_function																								;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp, 0xFF ST X+, temp	ldi temp, 0xFB ST X+, temp	ldi temp, 0xFB ST X+, temp	ldi temp, 0xFF ST X+, temp      ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
		Call Rain_Fall_function																								;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp, 0xFF ST X+, temp	ldi temp, 0xFB ST X+, temp	ldi temp, 0xFB ST X+, temp	ldi temp, 0xFE ST X+, temp      ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x01 ST X+, temp      ;
		Call Rain_Fall_function																								;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp, 0xFF ST X+, temp	ldi temp, 0xFB ST X+, temp	ldi temp, 0xFF ST X+, temp	ldi temp, 0xFE ST X+, temp      ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
		Call Rain_Fall_function Call Rain_Fall_function																		;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp, 0xFB ST X+, temp	ldi temp, 0xFB ST X+, temp	ldi temp, 0xFF ST X+, temp	ldi temp, 0xFE ST X+, temp      ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ldi temp, 0x04 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
		Call Rain_Fall_function																								;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp, 0xFB ST X+, temp	ldi temp, 0xFF ST X+, temp	ldi temp, 0xFF ST X+, temp	ldi temp, 0xFE ST X+, temp      ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
		Call Rain_Fall_function																								;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp, 0xFB ST X+, temp	ldi temp, 0xFF ST X+, temp	ldi temp, 0xFE ST X+, temp	ldi temp, 0xFE ST X+, temp      ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x01 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
		Call Rain_Fall_function																								;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp, 0xFB ST X+, temp	ldi temp, 0xFF ST X+, temp	ldi temp, 0xFE ST X+, temp	ldi temp, 0xFF ST X+, temp      ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
		Call Rain_Fall_function Call Rain_Fall_function																		;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp, 0xFB ST X+, temp	ldi temp, 0xFE ST X+, temp	ldi temp, 0xFE ST X+, temp	ldi temp, 0xFF ST X+, temp      ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x01 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
		Call Rain_Fall_function																								;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp, 0xFF ST X+, temp	ldi temp, 0xFE ST X+, temp	ldi temp, 0xFE ST X+, temp	ldi temp, 0xFF ST X+, temp      ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
		Call Rain_Fall_function Call Rain_Fall_function																		;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp, 0xFF ST X+, temp	ldi temp, 0xFE ST X+, temp	ldi temp, 0xBE ST X+, temp	ldi temp, 0xFF ST X+, temp      ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x40 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
		Call Rain_Fall_function																								;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp, 0xFF ST X+, temp	ldi temp, 0xFE ST X+, temp	ldi temp, 0xBF ST X+, temp	ldi temp, 0xFF ST X+, temp      ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
		Call Rain_Fall_function																								;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp, 0xFF ST X+, temp	ldi temp, 0xFE ST X+, temp	ldi temp, 0xBF ST X+, temp	ldi temp, 0xFF ST X+, temp      ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;

		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi temp, 0xFF ST X+, temp	ldi temp, 0xFF ST X+, temp	ldi temp, 0xBF ST X+, temp	ldi temp, 0xFF ST X+, temp      ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
		Call Rain_Fall_function																								;
		ldi Subtraction3, 1																									;
		CP Subtraction4, Subtraction3																						;
		BREQ Rain_Fall_end																									;
		DEC Subtraction4																									;
		rjmp Rain_Fall_loop																									;
Rain_Fall_end:																												;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ldi Byte_1, 0xFF ST X+, Byte_1	ldi Byte_2, 0xFF ST X+, Byte_2	ldi Byte_3, 0xFF ST X+, Byte_3 ldi Byte_4, 0xFF ST X+, Byte_4	;
		ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4	;
		ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4	;
		ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4	;
		ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4	;
		ldi temp_3, 185 ldi counter, 10 call bright																		;
		RET																													;
Rain_Fall_function:																											;
		ldi temp_3, 185 ldi counter, 10 call bright																			;
		ldi Xh, 0x00																										;
		ldi Xl, 0xBA																										;
		ld Byte_1, X+ ld Byte_2, X+ ld Byte_3, X+ ld Byte_4, X+															    ;
		ST X+, Byte_1 ST X+, Byte_2 ST X+, Byte_3 ST X+, Byte_4																;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB6																										;
		ld Byte_1, X+ ld Byte_2, X+ ld Byte_3, X+ ld Byte_4, X+															    ;
		ST X+, Byte_1 ST X+, Byte_2 ST X+, Byte_3 ST X+, Byte_4																;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ld Byte_1, X+ ld Byte_2, X+ ld Byte_3, X+ ld Byte_4, X+															    ;
		ST X+, Byte_1 ST X+, Byte_2 ST X+, Byte_3 ST X+, Byte_4																;
		ldi Xh, 0x00																										;
		RET																													;
																															;
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////