/*
 * Brightness.asm
 *
 *  Created: 4/10/2017 12:57:31 PM
 *   Author: qbake_0
 */ 
 /////////////////////////////////////////////////////////////
bright:														;
		MOV temp_2, temp_3									;
bright_loop:												;
		call five call four call three call two	call one	;
		dec counter											;	
		brne bright_loop									;
		RET													;
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
one:																																			;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x01																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne one_Bit1_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xAE																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xE8																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp one_Bit1_status_on																												;
one_Bit1_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xE8																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4		;
one_Bit1_status_on:																																;
			ldi counter_2, 1 call Lots_O_Lights_function																								;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x02																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne one_Bit2_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xAE																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xE8																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp one_Bit2_status_on																												;
one_Bit2_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xE8																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4		;
one_Bit2_status_on:																																;
			ldi counter_2, 2 call Lots_O_Lights_function																								;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x04																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne one_Bit3_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xAE																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xE8																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp one_Bit3_status_on																												;
one_Bit3_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xE8																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4       ;
one_Bit3_status_on:																																;
			ldi counter_2, 4 call Lots_O_Lights_function																								;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x08																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne one_Bit4_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xAE																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xE8																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp one_Bit4_status_on																												;
one_Bit4_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xE8																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4		;
one_Bit4_status_on:																																;
			ldi counter_2, 8 call Lots_O_Lights_function																								;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x10																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne one_Bit5_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xAE																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xE8																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp one_Bit5_status_on																												;
one_Bit5_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xE8																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4	    ;
one_Bit5_status_on:																																;
			ldi counter_2, 16 call Lots_O_Lights_function																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x20																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne one_Bit6_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xAE																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xE8																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp one_Bit6_status_on																												;
one_Bit6_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xE8																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4	    ;
one_Bit6_status_on:																																;
			ldi counter_2, 32 call Lots_O_Lights_function																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x40																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne one_Bit7_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xAE																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xE8																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp one_Bit7_status_on																												;
one_Bit7_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xE8																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4		;
one_Bit7_status_on:																																;
			ldi counter_2, 64 call Lots_O_Lights_function																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x80																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne one_Bit8_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xAE																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xE8																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp one_Bit8_status_on																												;
one_Bit8_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xE8																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4		;
one_Bit8_status_on:																																;
			ldi counter_2, 128 call Lots_O_Lights_function																							;
																																				;
			RET																																	;
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
two:																																			;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x01																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne two_Bit1_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xB2																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xEC																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp two_Bit1_status_on																												;
two_Bit1_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xEC																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4		;
two_Bit1_status_on:																																;
			ldi counter_2, 1 call Lots_O_Lights_function2																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x02																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne two_Bit2_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xB2																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xEC																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp two_Bit2_status_on																												;
two_Bit2_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xEC																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4		;
two_Bit2_status_on:																																;
			ldi counter_2, 2 call Lots_O_Lights_function2																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x04																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne two_Bit3_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xB2																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xEC																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp two_Bit3_status_on																												;
two_Bit3_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xEC																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4       ;
two_Bit3_status_on:																																;
			ldi counter_2, 4 call Lots_O_Lights_function2																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x08																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne two_Bit4_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xB2																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xEC																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp two_Bit4_status_on																												;
two_Bit4_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xEC																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4		;
two_Bit4_status_on:																																;
			ldi counter_2, 8 call Lots_O_Lights_function2																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x10																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne two_Bit5_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xB2																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xEC																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp two_Bit5_status_on																												;
two_Bit5_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xEC																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4	    ;
two_Bit5_status_on:																																;
			ldi counter_2, 16 call Lots_O_Lights_function2																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x20																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne two_Bit6_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xB2																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xEC																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp two_Bit6_status_on																												;
two_Bit6_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xEC																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4	    ;
two_Bit6_status_on:																																;
			ldi counter_2, 32 call Lots_O_Lights_function2																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x40																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne two_Bit7_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xB2																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xEC																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp two_Bit7_status_on																												;
two_Bit7_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xEC																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4		;
two_Bit7_status_on:																																;
			ldi counter_2, 64 call Lots_O_Lights_function2																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x80																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne two_Bit8_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xB2																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xEC																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp two_Bit8_status_on																												;
two_Bit8_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xEC																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4		;
two_Bit8_status_on:																																;
			ldi counter_2, 128 call Lots_O_Lights_function2																							;
																																				;
			RET																																	;
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
three:																																			;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x01																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne three_Bit1_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xB6																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xF0																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp three_Bit1_status_on																											;
three_Bit1_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xF0																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4		;
three_Bit1_status_on:																															;
			ldi counter_2, 1 call Lots_O_Lights_function3																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x02																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne three_Bit2_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xB6																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xF0																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp three_Bit2_status_on																											;
three_Bit2_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xF0																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4		;
three_Bit2_status_on:																															;
			ldi counter_2, 2 call Lots_O_Lights_function3																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x04																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne three_Bit3_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xB6																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xF0																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp three_Bit3_status_on																											;
three_Bit3_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xF0																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4       ;
three_Bit3_status_on:																															;
			ldi counter_2, 4 call Lots_O_Lights_function3																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x08																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne three_Bit4_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xB6																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xF0																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp three_Bit4_status_on																											;
three_Bit4_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xF0																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4		;
three_Bit4_status_on:																															;
			ldi counter_2, 8 call Lots_O_Lights_function3																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x10																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne three_Bit5_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xB6																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xF0																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp three_Bit5_status_on																											;
three_Bit5_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xF0																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4	    ;
three_Bit5_status_on:																															;
			ldi counter_2, 16 call Lots_O_Lights_function3																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x20																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne three_Bit6_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xB6																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xF0																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp three_Bit6_status_on																											;
three_Bit6_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xF0																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4	    ;
three_Bit6_status_on:																															;
			ldi counter_2, 32 call Lots_O_Lights_function3																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x40																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne three_Bit7_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xB6																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xF0																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp three_Bit7_status_on																											;
three_Bit7_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xF0																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4		;
three_Bit7_status_on:																															;
			ldi counter_2, 64 call Lots_O_Lights_function3																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x80																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne three_Bit8_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xB6																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xF0																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp three_Bit8_status_on																											;
three_Bit8_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xF0																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4		;
three_Bit8_status_on:																															;
			ldi counter_2, 128 call Lots_O_Lights_function3																							;
																																				;
			RET																																	;
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
four:																																			;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x01																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne four_Bit1_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xBA																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xF4																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp four_Bit1_status_on																											;
four_Bit1_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xF4																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4		;
four_Bit1_status_on:																															;
			ldi counter_2, 1 call Lots_O_Lights_function4																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x02																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne four_Bit2_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xBA																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xF4																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp four_Bit2_status_on																											;
four_Bit2_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xF4																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4		;
four_Bit2_status_on:																															;
			ldi counter_2, 2 call Lots_O_Lights_function4																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x04																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne four_Bit3_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xBA																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xF4																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp four_Bit3_status_on																											;
four_Bit3_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xF4																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4       ;
four_Bit3_status_on:																															;
			ldi counter_2, 4 call Lots_O_Lights_function4																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x08																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne four_Bit4_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xBA																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xF4																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp four_Bit4_status_on																											;
four_Bit4_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xF4																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4		;
four_Bit4_status_on:																															;
			ldi counter_2, 8 call Lots_O_Lights_function4																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x10																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne four_Bit5_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xBA																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xF4																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp four_Bit5_status_on																											;
four_Bit5_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xF4																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4	    ;
four_Bit5_status_on:																															;
			ldi counter_2, 16 call Lots_O_Lights_function4																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x20																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne four_Bit6_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xBA																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xF4																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp four_Bit6_status_on																											;
four_Bit6_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xF4																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4	    ;
four_Bit6_status_on:																															;
			ldi counter_2, 32 call Lots_O_Lights_function4																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x40																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne four_Bit7_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xBA																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xF4																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp four_Bit7_status_on																											;
four_Bit7_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xF4																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4		;
four_Bit7_status_on:																															;
			ldi counter_2, 64 call Lots_O_Lights_function4																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x80																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne four_Bit8_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xBA																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xF4																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp four_Bit8_status_on																											;
four_Bit8_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xF4																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4		;
four_Bit8_status_on:																															;
			ldi counter_2, 128 call Lots_O_Lights_function4																							;
																																				;
			RET																																	;
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
five:																																			;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x01																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne five_Bit1_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xBE																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xF8																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp five_Bit1_status_on																											;
five_Bit1_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xF8																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4		;
five_Bit1_status_on:																															;
			ldi counter_2, 1 call Lots_O_Lights_function5																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x02																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne five_Bit2_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xBE																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xF8																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp five_Bit2_status_on																											;
five_Bit2_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xF8																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4		;
five_Bit2_status_on:																															;
			ldi counter_2, 2 call Lots_O_Lights_function5																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x04																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne five_Bit3_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xBE																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xF8																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp five_Bit3_status_on																											;
five_Bit3_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xF8																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4       ;
five_Bit3_status_on:																															;
			ldi counter_2, 4 call Lots_O_Lights_function5																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x08																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne five_Bit4_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xBE																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xF8																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp five_Bit4_status_on																											;
five_Bit4_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xF8																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4		;
five_Bit4_status_on:																															;
			ldi counter_2, 8 call Lots_O_Lights_function5																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x10																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne five_Bit5_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xBE																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xF8																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp five_Bit5_status_on																											;
five_Bit5_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xF8																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4	    ;
five_Bit5_status_on:																															;
			ldi counter_2, 16 call Lots_O_Lights_function5																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x20																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne five_Bit6_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xBE																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xF8																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp five_Bit6_status_on																											;
five_Bit6_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xF8																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4	    ;
five_Bit6_status_on:																															;
			ldi counter_2, 32 call Lots_O_Lights_function5																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x40																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne five_Bit7_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xBE																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xF8																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp five_Bit7_status_on																											;
five_Bit7_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xF8																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4		;
five_Bit7_status_on:																															;
			ldi counter_2, 64 call Lots_O_Lights_function5																							;
																																				;
			MOV temp_4, temp_2																													;
			ldi temp_3, 0x80																													;
			AND temp_4, temp_3																													;
			CP temp_4, temp_3																													;
			brne five_Bit8_status_off																											;
			ldi Xh, 0x00 ldi Xl, 0xBE																											;
			LD Byte_1, X+ LD Byte_2, X+ LD Byte_3, X+ LD Byte_4, X+																				;
			ldi Xh, 0x00 ldi Xl, 0xF8																											;
			ST X+, Byte_1	ST X+, Byte_2 ST X+, Byte_3	ST X+, Byte_4																			;
			rjmp five_Bit8_status_on																											;
five_Bit8_status_off:																															;
			ldi Xh, 0x00 ldi Xl, 0xF8																											;
			ldi Byte_1, 0x00 ST X+, Byte_1	ldi Byte_2, 0x00 ST X+, Byte_2	ldi Byte_3, 0x00 ST X+, Byte_3 ldi Byte_4, 0x00 ST X+, Byte_4		;
five_Bit8_status_on:																															;
			ldi counter_2, 128 call Lots_O_Lights_function5																							;
																																				;
			RET																																	;
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Lots_O_Lights_function:													;
			ldi Xh, 0x00											;
			ldi Xl, 0xE8											;
			LD Byte_1, X+											;
			LD Byte_2, X+											;
			LD Byte_3, X+											;
			LD Byte_4, X+											;
			ldi temp, 0b10000000									;
			Call Layers_status										;
O_start:	Call SPI_MasterTransmit Call Latch						;		
			dec counter_2											;
			brne O_start											;
			RET														;
																	;
Lots_O_Lights_function2:													;
			ldi Xh, 0x00											;
			ldi Xl, 0xEC											;
			LD Byte_1, X+											;
			LD Byte_2, X+											;
			LD Byte_3, X+											;
			LD Byte_4, X+											;
			ldi temp, 0b01000000									;
			Call Layers_status										;
O_start2:	Call SPI_MasterTransmit Call Latch						;		
			dec counter_2											;
			brne O_start2											;
			RET														;
																	;
Lots_O_Lights_function3:													;
			ldi Xh, 0x00											;
			ldi Xl, 0xF0											;
			LD Byte_1, X+											;
			LD Byte_2, X+											;
			LD Byte_3, X+											;
			LD Byte_4, X+											;
			ldi temp, 0b00100000									;
			Call Layers_status										;
O_start3:	Call SPI_MasterTransmit Call Latch						;		
			dec counter_2											;
			brne O_start3											;
			RET														;
																	;
Lots_O_Lights_function4:													;
			ldi Xh, 0x00											;
			ldi Xl, 0xF4											;
			LD Byte_1, X+											;
			LD Byte_2, X+											;
			LD Byte_3, X+											;
			LD Byte_4, X+											;
			ldi temp, 0b00010000									;
			Call Layers_status										;
O_start4:	Call SPI_MasterTransmit Call Latch						;		
			dec counter_2											;
			brne O_start4											;
			RET														;
																	;
Lots_O_Lights_function5:													;
			ldi Xh, 0x00											;
			ldi Xl, 0xF8											;
			LD Byte_1, X+											;
			LD Byte_2, X+											;
			LD Byte_3, X+											;
			LD Byte_4, X+											;
			ldi temp, 0b00001000									;
			Call Layers_status										;
O_start5:	Call SPI_MasterTransmit Call Latch						;		
			dec counter_2											;
			brne O_start5											;
			RET														;
/////////////////////////////////////////////////////////////////////
