/*
 * Expand_Animation.asm
 *
 *  Created: 4/10/2017 11:10:27 AM
 *   Author: qbake_0
 */ 
 ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
 Expand_4:																														;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x10 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x18 ST X+, temp	ldi temp, 0x03 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x18 ST X+, temp	ldi temp, 0x03 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x9C ST X+, temp	ldi temp, 0x72 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x14 ST X+, temp	ldi temp, 0x50 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x9C ST X+, temp	ldi temp, 0x72 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x5E ST X+, temp	ldi temp, 0x4A ST X+, temp	ldi temp, 0x0F ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x12 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x09 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x12 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x09 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x5E ST X+, temp	ldi temp, 0x4A ST X+, temp	ldi temp, 0x0F ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x3F ST X+, temp	ldi temp, 0xC6 ST X+, temp	ldi temp, 0xF8 ST X+, temp	ldi temp, 0x0F ST X+, temp      ;
			ldi temp, 0x11 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x10 ST X+, temp	ldi temp, 0x0F ST X+, temp      ;
			ldi temp, 0x11 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x10 ST X+, temp	ldi temp, 0x0F ST X+, temp      ;
			ldi temp, 0x11 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x10 ST X+, temp	ldi temp, 0x0F ST X+, temp      ;
			ldi temp, 0x3F ST X+, temp	ldi temp, 0xC6 ST X+, temp	ldi temp, 0xF8 ST X+, temp	ldi temp, 0x0F ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 62 call bright																			;
			/////
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0xE0 ST X+, temp	ldi temp, 0xA5 ST X+, temp	ldi temp, 0xF4 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x20 ST X+, temp	ldi temp, 0x01 ST X+, temp	ldi temp, 0x90 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x20 ST X+, temp	ldi temp, 0x01 ST X+, temp	ldi temp, 0x90 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0xE0 ST X+, temp	ldi temp, 0xA5 ST X+, temp	ldi temp, 0xF4 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x9C ST X+, temp	ldi temp, 0x72 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x14 ST X+, temp	ldi temp, 0x50 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x9C ST X+, temp	ldi temp, 0x72 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x80 ST X+, temp	ldi temp, 0x31 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x80 ST X+, temp	ldi temp, 0x31 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x10 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x80 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 10 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x04 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 10 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x20 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 10 call bright																			;
																																;
			RET																													;
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Expand_3:////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////																													
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x01 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x8C ST X+, temp	ldi temp, 0x01 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x8C ST X+, temp	ldi temp, 0x01 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x70 ST X+, temp	ldi temp, 0xCA ST X+, temp	ldi temp, 0x01 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x50 ST X+, temp	ldi temp, 0x40 ST X+, temp	ldi temp, 0x01 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x70 ST X+, temp	ldi temp, 0xCA ST X+, temp	ldi temp, 0x01 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0xC0 ST X+, temp	ldi temp, 0x4B ST X+, temp	ldi temp, 0xE9 ST X+, temp	ldi temp, 0x01 ST X+, temp      ;
			ldi temp, 0x40 ST X+, temp	ldi temp, 0x02 ST X+, temp	ldi temp, 0x20 ST X+, temp	ldi temp, 0x01 ST X+, temp      ;
			ldi temp, 0x40 ST X+, temp	ldi temp, 0x02 ST X+, temp	ldi temp, 0x20 ST X+, temp	ldi temp, 0x01 ST X+, temp      ;
			ldi temp, 0xC0 ST X+, temp	ldi temp, 0x4B ST X+, temp	ldi temp, 0xE9 ST X+, temp	ldi temp, 0x01 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x3F ST X+, temp	ldi temp, 0xC6 ST X+, temp	ldi temp, 0xF8 ST X+, temp	ldi temp, 0x0F ST X+, temp      ;
			ldi temp, 0x11 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x10 ST X+, temp	ldi temp, 0x0F ST X+, temp      ;
			ldi temp, 0x11 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x10 ST X+, temp	ldi temp, 0x0F ST X+, temp      ;
			ldi temp, 0x11 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x10 ST X+, temp	ldi temp, 0x0F ST X+, temp      ;
			ldi temp, 0x3F ST X+, temp	ldi temp, 0xC6 ST X+, temp	ldi temp, 0xF8 ST X+, temp	ldi temp, 0x0F ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 62 call bright																			;
			//////////////////////////////////
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x2F ST X+, temp	ldi temp, 0xA5 ST X+, temp	ldi temp, 0x07 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x09 ST X+, temp	ldi temp, 0x80 ST X+, temp	ldi temp, 0x04 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x09 ST X+, temp	ldi temp, 0x80 ST X+, temp	ldi temp, 0x04 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x2F ST X+, temp	ldi temp, 0xA5 ST X+, temp	ldi temp, 0x07 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0xA7 ST X+, temp	ldi temp, 0x1C ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x05 ST X+, temp	ldi temp, 0x14 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0xA7 ST X+, temp	ldi temp, 0x1C ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x63 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x63 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x01 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x02 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 10 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x04 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 10 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x08 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 10 call bright																			;
			RET																													;
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Expand_2:////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////																													
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x10 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x80 ST X+, temp	ldi temp, 0x31 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x80 ST X+, temp	ldi temp, 0x31 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x9C ST X+, temp	ldi temp, 0x72 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x14 ST X+, temp	ldi temp, 0x50 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x9C ST X+, temp	ldi temp, 0x72 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0xE0 ST X+, temp	ldi temp, 0xA5 ST X+, temp	ldi temp, 0xF4 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x20 ST X+, temp	ldi temp, 0x01 ST X+, temp	ldi temp, 0x90 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x20 ST X+, temp	ldi temp, 0x01 ST X+, temp	ldi temp, 0x90 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0xE0 ST X+, temp	ldi temp, 0xA5 ST X+, temp	ldi temp, 0xF4 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x3F ST X+, temp	ldi temp, 0xC6 ST X+, temp	ldi temp, 0xF8 ST X+, temp	ldi temp, 0x0F ST X+, temp      ;
			ldi temp, 0x11 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x10 ST X+, temp	ldi temp, 0x0F ST X+, temp      ;
			ldi temp, 0x11 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x10 ST X+, temp	ldi temp, 0x0F ST X+, temp      ;
			ldi temp, 0x11 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x10 ST X+, temp	ldi temp, 0x0F ST X+, temp      ;
			ldi temp, 0x3F ST X+, temp	ldi temp, 0xC6 ST X+, temp	ldi temp, 0xF8 ST X+, temp	ldi temp, 0x0F ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 62 call bright																			;
			////////////////////////////////
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x5E ST X+, temp	ldi temp, 0x4A ST X+, temp	ldi temp, 0x0F ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x12 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x09 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x12 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x09 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x5E ST X+, temp	ldi temp, 0x4A ST X+, temp	ldi temp, 0x0F ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x9C ST X+, temp	ldi temp, 0x72 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x14 ST X+, temp	ldi temp, 0x50 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x9C ST X+, temp	ldi temp, 0x72 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x18 ST X+, temp	ldi temp, 0x03 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x18 ST X+, temp	ldi temp, 0x03 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x10 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x02 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 10 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x40 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 10 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x08 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 10 call bright																			;
			RET																													;
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Expand_1:
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x01 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x63 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x63 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0xA7 ST X+, temp	ldi temp, 0x1C ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x05 ST X+, temp	ldi temp, 0x14 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0xA7 ST X+, temp	ldi temp, 0x1C ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x2F ST X+, temp	ldi temp, 0xA5 ST X+, temp	ldi temp, 0x07 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x09 ST X+, temp	ldi temp, 0x80 ST X+, temp	ldi temp, 0x04 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x09 ST X+, temp	ldi temp, 0x80 ST X+, temp	ldi temp, 0x04 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x2F ST X+, temp	ldi temp, 0xA5 ST X+, temp	ldi temp, 0x07 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x3F ST X+, temp	ldi temp, 0xC6 ST X+, temp	ldi temp, 0xF8 ST X+, temp	ldi temp, 0x0F ST X+, temp      ;
			ldi temp, 0x11 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x10 ST X+, temp	ldi temp, 0x0F ST X+, temp      ;
			ldi temp, 0x11 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x10 ST X+, temp	ldi temp, 0x0F ST X+, temp      ;
			ldi temp, 0x11 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x10 ST X+, temp	ldi temp, 0x0F ST X+, temp      ;
			ldi temp, 0x3F ST X+, temp	ldi temp, 0xC6 ST X+, temp	ldi temp, 0xF8 ST X+, temp	ldi temp, 0x0F ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 62 call bright																		;
			//////////////////////////////////////////////////////////////
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0xC0 ST X+, temp	ldi temp, 0x4B ST X+, temp	ldi temp, 0xE9 ST X+, temp	ldi temp, 0x01 ST X+, temp      ;
			ldi temp, 0x40 ST X+, temp	ldi temp, 0x02 ST X+, temp	ldi temp, 0x20 ST X+, temp	ldi temp, 0x01 ST X+, temp      ;
			ldi temp, 0x40 ST X+, temp	ldi temp, 0x02 ST X+, temp	ldi temp, 0x20 ST X+, temp	ldi temp, 0x01 ST X+, temp      ;
			ldi temp, 0xC0 ST X+, temp	ldi temp, 0x4B ST X+, temp	ldi temp, 0xE9 ST X+, temp	ldi temp, 0x01 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x70 ST X+, temp	ldi temp, 0xCA ST X+, temp	ldi temp, 0x01 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x50 ST X+, temp	ldi temp, 0x40 ST X+, temp	ldi temp, 0x01 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x70 ST X+, temp	ldi temp, 0xCA ST X+, temp	ldi temp, 0x01 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x8C ST X+, temp	ldi temp, 0x01 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x8C ST X+, temp	ldi temp, 0x01 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x01 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 15 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x80 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 10 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x40 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 10 call bright																			;
																																;
			ldi Xh, 0x00																										;
			ldi Xl, 0xAE																										;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp      ;
			ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x20 ST X+, temp	ldi temp, 0x02 ST X+, temp      ;
			ldi temp_3, 115 ldi counter, 10 call bright																			;
																																;
			RET																													;
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////;
