/*
 * AsmFile3.asm
 *
 *  Created: 4/10/2017 1:23:08 AM
 *   Author: qbake_0
 */ 

Light_Rail:																												;
		ldi Xh, 0x00																									;
		ldi Xl, 0xA6																									;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	;
		ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	;
		ldi temp, 0xFF ST X+, temp	ldi temp, 0xFF ST X+, temp	ldi temp, 0xFF ST X+, temp	ldi temp, 0x01 ST X+, temp	;
		ldi temp_3, 255 ldi counter, 15 call bright																		;
																														;
		ldi Xh, 0x00																									;
		ldi Xl, 0xAA ldi temp, 0x01 ST X, temp Call LR2																	;
		ldi Xl, 0xAC ldi temp, 0x01 ST X, temp Call LR2																	;
		ldi Xl, 0xAB ldi temp, 0x10 ST X, temp Call LR2																	;
		ldi Xl, 0xAC ldi temp, 0x20 ST X, temp Call LR2///																;
		ldi Xl, 0xAA ldi temp, 0x08 ST X, temp Call LR2///																:
		ldi Xl, 0xAC ldi temp, 0x02 ST X, temp Call LR2///																;
		ldi Xl, 0xAB ldi temp, 0x20 ST X, temp Call LR2///																;
		ldi Xl, 0xAA ldi temp, 0x04 ST X, temp Call LR2																	;	
		ldi Xl, 0xAB ldi temp, 0x80 ST X, temp Call LR2///																; 
		ldi Xl, 0xAA ldi temp, 0x80 ST X, temp Call LR2///																;
		ldi Xl, 0xAA ldi temp, 0x10 ST X, temp Call LR2 																;
		ldi Xl, 0xAC ldi temp, 0x10 ST X, temp Call LR2																	;
		ldi Xl, 0xAA ldi temp, 0x80 ST X, temp Call LR1///																;
		ldi Xl, 0xAB ldi temp, 0x01 ST X, temp Call LR2																	;
		ldi Xl, 0xAB ldi temp, 0x20 ST X, temp Call LR1///																;
		ldi Xl, 0xAA ldi temp, 0x02 ST X, temp Call LR2///																;
		ldi Xl, 0xAB ldi temp, 0x02 ST X, temp Call LR2///																;
		ldi Xl, 0xAC ldi temp, 0x04 ST X, temp Call LR2																	;
		ldi Xl, 0xAB ldi temp, 0x80 ST X, temp Call LR1///																;
		ldi Xl, 0xAB ldi temp, 0x40 ST X, temp Call LR2																	;
		ldi Xl, 0xAC ldi temp, 0x20 ST X, temp Call LR1///																;
		ldi Xl, 0xAD ldi temp, 0x01 ST X, temp Call LR2																	;
		ldi Xl, 0xAB ldi temp, 0x02 ST X, temp Call LR1///																;
		ldi Xl, 0xAA ldi temp, 0x02 ST X, temp Call LR1///																;
		ldi Xl, 0xAC ldi temp, 0x40 ST X, temp Call LR2																	;
		ldi Xl, 0xAC ldi temp, 0x02 ST X, temp Call LR1///																;
		ldi Xl, 0xAB ldi temp, 0x04 ST X, temp Call LR2																	;
		ldi Xl, 0xAA ldi temp, 0x40 ST X, temp Call LR2																	;
		ldi Xl, 0xAA ldi temp, 0x08 ST X, temp Call LR1///																;																
		RET																												;
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Light_Rail2:
		ldi Xl, 0xAC ldi temp, 0x04 ST X, temp Call LR1																	;
		ldi Xl, 0xAB ldi temp, 0x80 ST X, temp Call LR2///																;
		ldi Xl, 0xAB ldi temp, 0x40 ST X, temp Call LR1																	;
		ldi Xl, 0xAC ldi temp, 0x20 ST X, temp Call LR2///																;
		ldi Xl, 0xAD ldi temp, 0x01 ST X, temp Call LR1																	;
		ldi Xl, 0xAB ldi temp, 0x02 ST X, temp Call LR2///																;
		ldi Xl, 0xAA ldi temp, 0x02 ST X, temp Call LR2///																;
		ldi Xl, 0xAC ldi temp, 0x40 ST X, temp Call LR1																	;
		ldi Xl, 0xAC ldi temp, 0x02 ST X, temp Call LR2///																;
		ldi Xl, 0xAB ldi temp, 0x04 ST X, temp Call LR1																	;
		ldi Xl, 0xAA ldi temp, 0x40 ST X, temp Call LR1																	;
		ldi Xl, 0xAA ldi temp, 0x08 ST X, temp Call LR2///																;
		ldi Xl, 0xAC ldi temp, 0x04 ST X, temp Call LR2																	;
		ldi Xl, 0xAB ldi temp, 0x80 ST X, temp Call LR1///																;
		ldi Xl, 0xAB ldi temp, 0x40 ST X, temp Call LR2																	;
		ldi Xl, 0xAC ldi temp, 0x20 ST X, temp Call LR1///																;
		ldi Xl, 0xAD ldi temp, 0x01 ST X, temp Call LR2																	;
		ldi Xl, 0xAB ldi temp, 0x02 ST X, temp Call LR1///																;
		ldi Xl, 0xAA ldi temp, 0x02 ST X, temp Call LR1///																;
		ldi Xl, 0xAC ldi temp, 0x40 ST X, temp Call LR2																	;
		ldi Xl, 0xAC ldi temp, 0x02 ST X, temp Call LR1///																;
		ldi Xl, 0xAB ldi temp, 0x04 ST X, temp Call LR2																	;
		ldi Xl, 0xAA ldi temp, 0x40 ST X, temp Call LR2																	;
		ldi Xl, 0xAA ldi temp, 0x08 ST X, temp Call LR1///																;

		ldi Xl, 0xAC ldi temp, 0x04 ST X, temp Call LR1																	;
		ldi Xl, 0xAB ldi temp, 0x80 ST X, temp Call LR2///																;
		ldi Xl, 0xAB ldi temp, 0x40 ST X, temp Call LR1																	;
		ldi Xl, 0xAC ldi temp, 0x20 ST X, temp Call LR2///																;
		ldi Xl, 0xAD ldi temp, 0x01 ST X, temp Call LR1																	;
		ldi Xl, 0xAB ldi temp, 0x02 ST X, temp Call LR2///																;
		ldi Xl, 0xAA ldi temp, 0x02 ST X, temp Call LR2///																;
		ldi Xl, 0xAC ldi temp, 0x40 ST X, temp Call LR1																	;
		ldi Xl, 0xAC ldi temp, 0x02 ST X, temp Call LR2///																;
		ldi Xl, 0xAB ldi temp, 0x04 ST X, temp Call LR1																	;
		ldi Xl, 0xAA ldi temp, 0x40 ST X, temp Call LR1																	;
		ldi Xl, 0xAA ldi temp, 0x08 ST X, temp Call LR2///																;
		ldi Xl, 0xAC ldi temp, 0x04 ST X, temp Call LR2																	;
		ldi Xl, 0xAB ldi temp, 0x80 ST X, temp Call LR1///																;
		ldi Xl, 0xAB ldi temp, 0x40 ST X, temp Call LR2																	;
		ldi Xl, 0xAC ldi temp, 0x20 ST X, temp Call LR1///																;
		ldi Xl, 0xAD ldi temp, 0x01 ST X, temp Call LR2																	;
		ldi Xl, 0xAB ldi temp, 0x02 ST X, temp Call LR1///																;
		ldi Xl, 0xAA ldi temp, 0x02 ST X, temp Call LR1///																;
		ldi Xl, 0xAC ldi temp, 0x40 ST X, temp Call LR2																	;
		ldi Xl, 0xAC ldi temp, 0x02 ST X, temp Call LR1///																;
		ldi Xl, 0xAB ldi temp, 0x04 ST X, temp Call LR2																	;
		ldi Xl, 0xAA ldi temp, 0x40 ST X, temp Call LR2																	;
		ldi Xl, 0xAA ldi temp, 0x08 ST X, temp Call LR1///																;
		ldi Xl, 0xAC ldi temp, 0x04 ST X, temp Call LR1																	;
		ldi Xl, 0xAB ldi temp, 0x80 ST X, temp Call LR2///																;
		ldi Xl, 0xAB ldi temp, 0x40 ST X, temp Call LR1																	;
		ldi Xl, 0xAC ldi temp, 0x20 ST X, temp Call LR2///																;
		ldi Xl, 0xAD ldi temp, 0x01 ST X, temp Call LR1																	;
		ldi Xl, 0xAB ldi temp, 0x02 ST X, temp Call LR2///																;
		ldi Xl, 0xAA ldi temp, 0x02 ST X, temp Call LR2///																;
		ldi Xl, 0xAC ldi temp, 0x40 ST X, temp Call LR1																	;
		ldi Xl, 0xAC ldi temp, 0x02 ST X, temp Call LR2///																;
		ldi Xl, 0xAB ldi temp, 0x04 ST X, temp Call LR1																	;
		ldi Xl, 0xAA ldi temp, 0x40 ST X, temp Call LR1																	;
		ldi Xl, 0xAA ldi temp, 0x08 ST X, temp Call LR2///																;
		ldi Xl, 0xAC ldi temp, 0x04 ST X, temp Call LR2																	;
		ldi Xl, 0xAB ldi temp, 0x80 ST X, temp Call LR1///																;
		ldi Xl, 0xAB ldi temp, 0x40 ST X, temp Call LR2																	;
		ldi Xl, 0xAC ldi temp, 0x20 ST X, temp Call LR1///																;
		ldi Xl, 0xAD ldi temp, 0x01 ST X, temp Call LR2																	;
		ldi Xl, 0xAB ldi temp, 0x02 ST X, temp Call LR1///																;
		ldi Xl, 0xAA ldi temp, 0x02 ST X, temp Call LR1///																;
		ldi Xl, 0xAC ldi temp, 0x40 ST X, temp Call LR2																	;
		ldi Xl, 0xAC ldi temp, 0x02 ST X, temp Call LR1///																;
		ldi Xl, 0xAB ldi temp, 0x04 ST X, temp Call LR2																	;
		ldi Xl, 0xAA ldi temp, 0x40 ST X, temp Call LR2																	;
		ldi Xl, 0xAA ldi temp, 0x08 ST X, temp Call LR1///																;
		ldi Xl, 0xAC ldi temp, 0x04 ST X, temp Call LR1																	;
		ldi Xl, 0xAB ldi temp, 0x80 ST X, temp Call LR2///																;
		ldi Xl, 0xAB ldi temp, 0x40 ST X, temp Call LR1																	;
		ldi Xl, 0xAC ldi temp, 0x20 ST X, temp Call LR2///																;
		ldi Xl, 0xAD ldi temp, 0x01 ST X, temp Call LR1																	;
		ldi Xl, 0xAB ldi temp, 0x02 ST X, temp Call LR2///																;
		ldi Xl, 0xAA ldi temp, 0x02 ST X, temp Call LR2///																;
		ldi Xl, 0xAC ldi temp, 0x40 ST X, temp Call LR1																	;
		ldi Xl, 0xAC ldi temp, 0x02 ST X, temp Call LR2///																;
		ldi Xl, 0xAB ldi temp, 0x04 ST X, temp Call LR1																	;
		ldi Xl, 0xAA ldi temp, 0x40 ST X, temp Call LR1																	;
		ldi Xl, 0xAA ldi temp, 0x08 ST X, temp Call LR2///																;
		ldi Xl, 0xAC ldi temp, 0x04 ST X, temp Call LR2																	;
		ldi Xl, 0xAB ldi temp, 0x80 ST X, temp Call LR1///																;
		ldi Xl, 0xAB ldi temp, 0x40 ST X, temp Call LR2																	;
		ldi Xl, 0xAC ldi temp, 0x20 ST X, temp Call LR1///																;
		ldi Xl, 0xAD ldi temp, 0x01 ST X, temp Call LR2																	;
		ldi Xl, 0xAB ldi temp, 0x02 ST X, temp Call LR1///																;
		ldi Xl, 0xAA ldi temp, 0x02 ST X, temp Call LR1///																;
		ldi Xl, 0xAC ldi temp, 0x40 ST X, temp Call LR2																	;
		ldi Xl, 0xAC ldi temp, 0x02 ST X, temp Call LR1///																;
		ldi Xl, 0xAB ldi temp, 0x04 ST X, temp Call LR2																	;
		ldi Xl, 0xAA ldi temp, 0x40 ST X, temp Call LR2																	;
		ldi Xl, 0xAA ldi temp, 0x08 ST X, temp Call LR1///																;
		RET																												;
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
LR1:																														;
		ldi Subtraction4, 5																									;
Light_Rail1_loop:																											;
		ldi Xh, 0x00																										;
		ldi Xl, 0xBA																										;
		ld Byte_1, X																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xBE																										;
		ld temp, X																											;
		OR Byte_1, temp																										;
		ST X, Byte_1																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xBB																										;
		ld Byte_2, X																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xBF																										;
		ld temp, X																											;
		OR Byte_2, temp																										;
		ST X, Byte_2																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xBC																										;
		ld Byte_3, X																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xC0																										;
		ld temp, X																											;
		OR Byte_3, temp																										;
		ST X, Byte_3																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xBD																										;
		ld Byte_4, X																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xC1																										;
		ld temp, X																											;
		OR Byte_4, temp																										;
		ST X, Byte_4																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB6																										;
		ld Byte_1, X+ ld Byte_2, X+ ld Byte_3, X+ ld Byte_4, X+															    ;
		ST X+, Byte_1 ST X+, Byte_2 ST X+, Byte_3 ST X+, Byte_4																;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ld Byte_1, X+ ld Byte_2, X+ ld Byte_3, X+ ld Byte_4, X+															    ;
		ST X+, Byte_1 ST X+, Byte_2 ST X+, Byte_3 ST X+, Byte_4																;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAA																										;
		ld Byte_1, X+ ld Byte_2, X+ ld Byte_3, X+ ld Byte_4, X+															    ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ST X+, Byte_1 ST X+, Byte_2 ST X+, Byte_3 ST X+, Byte_4																;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAA																										;
		ld temp, X																											;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ld Byte_1, X																										;
		Sub Byte_1, temp																									;
		ST X, Byte_1																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAB																										;
		ld temp, X																											;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAF																										;
		ld Byte_2, X																										;
		Sub Byte_2, temp																									;
		ST X, Byte_2																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAC																										;
		ld temp, X																											;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB0																										;
		ld Byte_3, X																										;
		Sub Byte_3, temp																									;
		ST X, Byte_3																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAD																										;
		ld temp, X																											;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB1																										;
		ld Byte_4, X																										;
		Sub Byte_4, temp																									;
		ST X, Byte_4																										;
																															;
		ldi Xl, 0xAA																										;
		ldi temp, 0x00																										;
		ST X+, temp ST X+, temp ST X+, temp ST X+, temp																		;
																															;
		ldi Subtraction3, 1																									;
		CP Subtraction4, Subtraction3																						;
		BREQ Light_Rail1_end																										;
		DEC Subtraction4																									;
		ldi temp_3, 255 ldi counter, 7 call bright																			;
		rjmp Light_Rail1_loop																										;
Light_Rail1_end:																													;
		ldi temp_3, 255 ldi counter, 22 call bright																			;
		RET																													;
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////;
LR2:																														;
		ldi Subtraction4, 5																									;
Light_Rail2_loop:																													;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ld Byte_1, X																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ld temp, X																											;
		OR Byte_1, temp																										;
		ST X, Byte_1																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB3																										;
		ld Byte_2, X																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAF																										;
		ld temp, X																											;
		OR Byte_2, temp																										;
		ST X, Byte_2																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB4																										;
		ld Byte_3, X																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB0																										;
		ld temp, X																											;
		OR Byte_3, temp																										;
		ST X, Byte_3																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB5																										;
		ld Byte_4, X																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB1																										;
		ld temp, X																											;
		OR Byte_4, temp																										;
		ST X, Byte_4																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB6																										;
		ld Byte_1, X+ ld Byte_2, X+ ld Byte_3, X+ ld Byte_4, X+															    ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ST X+, Byte_1 ST X+, Byte_2 ST X+, Byte_3 ST X+, Byte_4																;
		ldi Xh, 0x00																										;
		ldi Xl, 0xBA																										;
		ld Byte_1, X+ ld Byte_2, X+ ld Byte_3, X+ ld Byte_4, X+															    ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB6																										;
		ST X+, Byte_1 ST X+, Byte_2 ST X+, Byte_3 ST X+, Byte_4																;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAA																										;
		ld Byte_1, X+ ld Byte_2, X+ ld Byte_3, X+ ld Byte_4, X+															    ;
		ldi Xh, 0x00																										;
		ldi Xl, 0xBA																										;
		ST X+, Byte_1 ST X+, Byte_2 ST X+, Byte_3 ST X+, Byte_4																;
		
		ldi Xh, 0x00																										;
		ldi Xl, 0xAA																										;
		ld temp, X																											;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xBE																										;
		ld Byte_1, X																										;
		Sub Byte_1, temp																									;
		ST X, Byte_1																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAB																										;
		ld temp, X																											;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xBF																										;
		ld Byte_2, X																										;
		Sub Byte_2, temp																									;
		ST X, Byte_2																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAC																										;
		ld temp, X																											;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xC0																										;
		ld Byte_3, X																										;
		Sub Byte_3, temp																									;
		ST X, Byte_3																										;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAD																										;
		ld temp, X																											;
																															;
		ldi Xh, 0x00																										;
		ldi Xl, 0xC1																										;
		ld Byte_4, X																										;
		Sub Byte_4, temp																									;
		ST X, Byte_4																										;
																															;
		ldi Xl, 0xAA																										;
		ldi temp, 0x00																										;
		ST X+, temp ST X+, temp ST X+, temp ST X+, temp																		;
																															;
		ldi Subtraction3, 1																									;
		CP Subtraction4, Subtraction3																						;
		BREQ Light_Rail2_end																								;
		DEC Subtraction4																									;
		ldi temp_3, 255 ldi counter, 7 call bright																			;
		rjmp Light_Rail2_loop																								;
Light_Rail2_end:																											;
		ldi temp_3, 255 ldi counter, 22 call bright																			;
		RET																													;
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
