/*
 * Spiral_Animation.asm
 *
 *  Created: 4/10/2017 11:29:22 AM
 *   Author: qbake_0
 */ 
 /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Spiral:																														;
	ldi Xh, 0x00																											;
	ldi Xl, 0xAA																											;
	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
																															;
	ldi Subtraction4, 8																										;
Spiral_loop:																												;
																															;
	ldi Xh, 0x00																											;
	ldi Xl, 0xAE																											;
	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x04 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	Call Spiral_function																									;
																															;
	ldi Xh, 0x00																											;
	ldi Xl, 0xAE																											;
	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x02 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	Call Spiral_function																									;
																															;
	ldi Xh, 0x00																											;
	ldi Xl, 0xAE																											;
	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x01 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	Call Spiral_function																									;
																															;
	ldi Xh, 0x00																											;
	ldi Xl, 0xAE																											;
	ldi temp, 0x00 ST X+, temp	ldi temp, 0x08 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	Call Spiral_function																									;
																															;
	ldi Xh, 0x00																											;
	ldi Xl, 0xAE																											;
	ldi temp, 0x40 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	Call Spiral_function																									;
																															;
	ldi Xh, 0x00																											;
	ldi Xl, 0xAE																											;
	ldi temp, 0x80 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	Call Spiral_function																									;
																															;
	ldi Xh, 0x00																											;
	ldi Xl, 0xAE																											;
	ldi temp, 0x00 ST X+, temp	ldi temp, 0x01 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	Call Spiral_function																									;
																															;
	ldi Xh, 0x00																											;
	ldi Xl, 0xAE																											;
	ldi temp, 0x00 ST X+, temp	ldi temp, 0x20 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	Call Spiral_function																									;
																															;
	ldi Xh, 0x00																											;
	ldi Xl, 0xAE																											;
	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x04 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	Call Spiral_function																									;
																															;
	ldi Xh, 0x00																											;
	ldi Xl, 0xAE																											;
	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x02 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	Call Spiral_function																									;
																															;
	ldi Xh, 0x00																											;
	ldi Xl, 0xAE																											;
	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x01 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	Call Spiral_function																									;
																															;
	ldi Xh, 0x00																											;
	ldi Xl, 0xAE																											;
	ldi temp, 0x00 ST X+, temp	ldi temp, 0x08 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	Call Spiral_function																									;
																															;
	ldi Xh, 0x00																											;
	ldi Xl, 0xAE																											;
	ldi temp, 0x40 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	Call Spiral_function																									;
																															;
	ldi Xh, 0x00																											;
	ldi Xl, 0xAE																											;
	ldi temp, 0x80 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	Call Spiral_function																									;
																															;
	ldi Xh, 0x00																											;
	ldi Xl, 0xAE																											;
	ldi temp, 0x00 ST X+, temp	ldi temp, 0x01 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	Call Spiral_function																									;
																															;
	ldi Xh, 0x00																											;
	ldi Xl, 0xAE																											;
	ldi temp, 0x00 ST X+, temp	ldi temp, 0x20 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	Call Spiral_function																									;
																															;
	ldi Xh, 0x00																											;
	ldi Xl, 0xAE																											;
	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x04 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	Call Spiral_function																									;
																															;
	ldi Xh, 0x00																											;
	ldi Xl, 0xAE																											;
	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x02 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	Call Spiral_function																									;
																															;
	ldi Xh, 0x00																											;
	ldi Xl, 0xAE																											;
	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x01 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	Call Spiral_function																									;
																															;
	ldi Xh, 0x00																											;
	ldi Xl, 0xAE																											;
	ldi temp, 0x00 ST X+, temp	ldi temp, 0x08 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	Call Spiral_function																									;
																															;
	ldi Xh, 0x00																											;
	ldi Xl, 0xAE																											;
	ldi temp, 0x40 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	Call Spiral_function																									;
																															;
	ldi Xh, 0x00																											;
	ldi Xl, 0xAE																											;
	ldi temp, 0x80 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	Call Spiral_function																									;
																															;
	ldi Xh, 0x00																											;
	ldi Xl, 0xAE																											;
	ldi temp, 0x00 ST X+, temp	ldi temp, 0x01 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	Call Spiral_function																									;
																															;																		;
																															;
	ldi Subtraction3, 1																										;
	CP Subtraction4, Subtraction3																							;
	BREQ Spiral_end																											;
	DEC Subtraction4																										;
	rjmp Spiral_loop																										;	
Spiral_end:																													;
																															;
	ldi Xh, 0x00																											;
	ldi Xl, 0xAE																											;
	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	Call Spiral_function																									;
																															;
	ldi Xh, 0x00																											;
	ldi Xl, 0xAE																											;
	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	Call Spiral_function																									;
																															;
	ldi Xh, 0x00																											;
	ldi Xl, 0xAE																											;
	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	Call Spiral_function																									;
																															;
	ldi Xh, 0x00																											;
	ldi Xl, 0xAE																											;
	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	Call Spiral_function																									;
																															;
	ldi Xh, 0x00																											;
	ldi Xl, 0xAE																											;
	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp	ldi temp, 0x00 ST X+, temp			;
	Call Spiral_function																									;	
	RET																														;
Spiral_function:																											;
		ldi temp_3, 100 ldi counter, 11 call bright																			;
		ldi Xh, 0x00																										;
		ldi Xl, 0xBA																										;
		ld Byte_1, X+ ld Byte_2, X+ ld Byte_3, X+ ld Byte_4, X+															    ;
		ST X+, Byte_1 ST X+, Byte_2 ST X+, Byte_3 ST X+, Byte_4																;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB6																										;
		ld Byte_1, X+ ld Byte_2, X+ ld Byte_3, X+ ld Byte_4, X+															    ;
		ST X+, Byte_1 ST X+, Byte_2 ST X+, Byte_3 ST X+, Byte_4																;
		ldi Xh, 0x00																										;
		ldi Xl, 0xB2																										;
		ld Byte_1, X+ ld Byte_2, X+ ld Byte_3, X+ ld Byte_4, X+															    ;
		ST X+, Byte_1 ST X+, Byte_2 ST X+, Byte_3 ST X+, Byte_4																;
		ldi Xh, 0x00																										;
		ldi Xl, 0xAE																										;
		ld Byte_1, X+ ld Byte_2, X+ ld Byte_3, X+ ld Byte_4, X+															    ;
		ST X+, Byte_1 ST X+, Byte_2 ST X+, Byte_3 ST X+, Byte_4																;
		RET																													;
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
